config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[show update]
      devise_scope :user do
        post 'users/sign_in', to: 'sessions#create', defaults: { format: :json }
        delete 'users/sign_out', to: 'sessions#destroy', defaults: { format: :json }
        post 'users/sign_up', to: 'registrations#create', defaults: { format: :json }
      end
    end
  end

  devise_for :users, skip: %i[registrations passwords]
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jwt_blacklist.rb
class JwtBlacklist < ApplicationRecord
	include Devise::JWT::RevocationStrategies::Blacklist

	self.table_name = 'jwt_blacklist'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JwtBlacklist

  before_validation :generate_jti, on: :create

  validates :name, presence: true, length: { minimum: 2, maximum: 35 }
  validates :jti, presence: true

  mount_uploader :avatar, AvatarUploader

  private

  def generate_jti
    self.jti = SecureRandom.uuid
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  include Pundit

  private

  # https://github.com/wayne5540/pundit/commit/81b9bca985d6739fb7b880d63f8550d39c2fe730
  def policy(record)
    policy = "#{controller_path.classify}Policy"
    policies[record] ||= policy.constantize.new(current_user, record)
  end

  def user_not_authorized
    render json: { 'error': 'Forbidden', 'status': 403 }
  end
end

app/controllers/api/v1/registrations_controller.rb
module Api
  module V1
    class Api::V1::RegistrationsController < Devise::RegistrationsController
      skip_before_action :verify_authenticity_token

      respond_to :json

      private

      def respond_with(resource, _opts = {})
        render json: UserSerializer.new(resource)
      end

      def respond_to_on_destroy
        head :no_content
      end
    end
  end
end

app/controllers/api/v1/sessions_controller.rb
module Api
  module V1
    class Api::V1::SessionsController < Devise::SessionsController
      skip_before_action :verify_authenticity_token

      respond_to :json

      private

      def respond_with(resource, _opts = {})
        render json: UserSerializer.new(resource)
      end

      def respond_to_on_destroy
        head :no_content
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < Api::V1::BaseController
      skip_before_action :verify_authenticity_token
      before_action :authenticate_user!
      before_action :set_user

      def show
        authorize @user

        render json: UserSerializer.new(@user)
      end

      def update
        authorize @user

        if @user.update(user_params)
          render json: UserSerializer.new(@user)
        else
          render json: { 'error': 'Bad Request', 'status': 400 }
        end
      end

      private

      def set_user
        @user = User.find(params[:id])
      end

      def user_params
        params.require(:user).permit(:name, :email, :password)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def user_not_authorized
    flash[:alert] = t('pundit.not_authorized')
    redirect_to user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: %i[index new create]
  before_action -> { authorize @user }, except: %i[index new create]

  def index
    @pagy, @users = pagy(User.all.order(updated_at: :desc))
    authorize User
  end

  def new
    @user = User.new

    authorize @user
  end

  def show; end

  def edit; end

  def create
    @user = User.new(user_params)
    authorize @user

    if @user.save
      redirect_to root_path, notice: I18n.t('controllers.users.created')
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  def destroy
    @user.destroy

    redirect_to root_path, notice: I18n.t('controllers.users.destroyed')
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :avatar, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def flash_class(level)
    case level
    when 'notice' then 'alert alert-info'
    when 'success' then 'alert alert-success'
    when 'error' then 'alert alert-danger'
    when 'alert' then 'alert alert-warning'
    end
  end

  def user_avatar(user)
    if user.avatar?
      user.avatar.url
    else
      asset_path('avatar.jpg')
    end
  end

  def user_avatar_thumb(user)
    if user.avatar.file.present?
      user.avatar.thumb.url
    else
      asset_path('avatar.jpg')
    end
  end

  def user_avatar_min(user)
    if user.avatar.file.present?
      user.avatar.min.url
    else
      asset_path('avatar.jpg')
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end

  def page_is_create_user?
    params[:action] == 'create' || current_page?(action: 'new')
  end
end

app/views/layouts/_header.html.erb
<header class="row">
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light">
        <%= link_to t('app.name'), root_path, class: 'navbar-brand text-white' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between align-content-center" id="navbar">
          <% if policy(User).user_is_admin? %>

            <%= link_to 'Новый пользователь', new_user_path, class: 'btn btn-outline-light btn-sm', title: 'Новый пользователь' %>


            <%= link_to 'Выйти', destroy_user_session_path, data: { confirm: 'Вы уверены, что хотите выйти?' }, class: 'btn btn-outline-light btn-sm', title: 'Выйти' %>

          <% end %>
        </div>
      </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Панель управления</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render partial: 'layouts/header' %>
  <div class="row">
    <div id="content" class="container">
      <% flash.each do |key, value| %>
        <div class="mt-2 <%= flash_class(key) %>">
          <%= value %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/partials/_form_errors.html.erb
<% errors = model.errors %>
  <% if errors.any? %>
  <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    <div class="lead">
      В вашей форме <%= t :errors, count: errors.count %>
    </div>
    <ul>
      <% errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user, html: { multipart: true }, id: 'users-form') do |form| %>
  <%= render partial: 'partials/form_errors', locals: { model: @user } %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>
  <% if page_is_create_user? %>
    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class: 'form-control' %>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :avatar %>
    <p><%= image_tag(@user.avatar.thumb.url) if @user.avatar? %></p>
    <%= form.file_field :avatar %>
  </div>
  <div class="form-group">
    <%= form.submit 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', :back %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="user mb-3 mt-3 row justify-content-between">
  <div class="col-12 col-md-auto text-center">
    <%=link_to( image_tag(user_avatar_min(user)), user_path(user)) %>
  </div>
  <div class="col-12 col-md-4 text-center">
    <%= user.name %>
  </div>
  <div class="col-12 col-md-4 text-center"><%= user.email %></div>
  <div class="col-12 col-md-auto justify-content-end text-center">
    <%= link_to fa_icon('eye'), user_path(user), title: 'Просмотр' %>
    <%= link_to fa_icon('edit'), edit_user_path(user), title: 'Редактировать'  %>
    <%= link_to fa_icon('trash'), user, method: :delete, data: { confirm: 'Вы уверены?' }, title: 'Удалить', class: 'text-danger' %>
  </div>
</div>
<hr>

app/views/users/edit.html.erb
<div class="row mt-4 justify-content-center">
  <div class="col-md-6 col-12">
    <h1>Редактировать пользователя</h1>
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Пользователи</h1>
<div id="users-list">
  <%= render partial: 'user', collection: @users %>
</div>
<div class="mt-4 row">
  <div class="container overflow-auto">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row mt-4 justify-content-center">
  <div class="col-md-6 col-12">
    <h1>Новый пользователь</h1>
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row mt-4 justify-content-center">
  <div class="col-md-6 col-12 text-center">
    <h1><%= @user.name %></h1>
    <div id="user-info">
      <div class="row justify-content-center">
        <div class="col-12">
          <%= image_tag user_avatar(@user),class: 'rounded-circle img-fluid mb-4' %>
        </div>
        <div class="col-12">

          <p><span class="user-email"><%= @user.email %></span></p>

        </div>
        <div class="col-auto">
          <%= link_to 'Редактировать', edit_user_path(@user), class: 'btn btn-primary mr-2', title: 'Редактировать'  %>
          <%= link_to 'Назад', root_path, class: 'btn btn-secondary ml-2', title: 'Назад'  %>
        </div>

      </div>
    </div>
  </div>
</div>